image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew

artifacts:
  - path: app-order.jar
    name: jarfile


#  - java -jar "./artifacts/app-order.jar" &


build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации

