image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

#artifacts:
#  - path: artifacts/app-order.jar
#    name: app-order
#
install:
  - chmod +x gradlew


#  - java -jar "./artifacts/app-order.jar" &


build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации

artifacts:
  - path: app-order.jar

